### ISSUE TITLE
运行出具错 terminate called after throwing an instance of 'std::invalid_argument'

### ISSUE THREAD

**Issue by wuming122333** [DCSI2022/AFLI_Calib#1]
wolfy@wolfy-DELL:~/calib/AFLI_Calib$ source ./devel/setup.bash
wolfy@wolfy-DELL:~/calib/AFLI_Calib$ roslaunch afli_calib run.launch 
... logging to /home/wolfy/.ros/log/e694a518-6516-11ef-a755-25cc4ebfc494/roslaunch-wolfy-DELL-525997.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wolfy-DELL:45723/

SUMMARY
========

PARAMETERS
 * /afl_lidarOdometry/lidar_topic: /velodyne_points
 * /afl_lidarOdometry/lidar_type: 2
 * /afl_lidarOdometry/match_stability_threshold: 0.5
 * /afl_lidarOdometry/motion_linearity_threshold: 0.1
 * /afl_lidarOdometry/rosbag_end: 200
 * /afl_lidarOdometry/rosbag_path: /media/wolfy/DATA...
 * /afl_lidarOdometry/rosbag_start: 0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    afl_lidarOdometry (afli_calib/afl_lidarOdometry)

ROS_MASTER_URI=http://localhost:11311

process[afl_lidarOdometry-1]: started with pid [526018]
Multi thread started 
Let's start!
the bag processed is: afl_lidarOdometry-1.log
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
[afl_lidarOdometry-1] process has died [pid 526018, exit code -6, cmd /home/wolfy/calib/AFLI_Calib/devel/lib/afli_calib/afl_lidarOdometry __name:=afl_lidarOdometry __log:=/home/wolfy/.ros/log/e694a518-6516-11ef-a755-25cc4ebfc494/afl_lidarOdometry-1.log].
log file: /home/wolfy/.ros/log/e694a518-6516-11ef-a755-25cc4ebfc494/afl_lidarOdometry-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by wuming122333** [comment]
launch文件中的内容：
<launch>
  
  <arg name="rosbag_path" default="/media/wolfy/DATA/test_RS2VLP.bag"/>
  <arg name="lidar_type" default="2"/>
  <arg name="lidar_topic" default="/velodyne_points"/>
  <arg name="match_stability_threshold" default="0.5"/>
  <arg name="motion_linearity_threshold" default="0.1"/>
  <arg name="rosbag_start" default="0"/>
  <arg name="rosbag_end" default="200"/>

  
  <node name="afl_lidarOdometry" pkg="afli_calib" type="afl_lidarOdometry" output="screen">
    <param name="rosbag_path" value="$(arg rosbag_path)"/>
    <param name="lidar_type" value="$(arg lidar_type)"/>
    <param name="lidar_topic" value="$(arg lidar_topic)"/>
    <param name="match_stability_threshold" value="$(arg match_stability_threshold)"/>
    <param name="motion_linearity_threshold" value="$(arg motion_linearity_threshold)"/>
    <param name="rosbag_start" value="$(arg rosbag_start)"/>
    <param name="rosbag_end" value="$(arg rosbag_end)"/>
  </node>
</launch>

**Comment by wuming122333** [comment]
launch文件中的内容：
<launch>
  
  <arg name="rosbag_path" default="/media/wolfy/DATA/test_RS2VLP.bag"/>
  <arg name="lidar_type" default="2"/>
  <arg name="lidar_topic" default="/velodyne_points"/>
  <arg name="match_stability_threshold" default="0.5"/>
  <arg name="motion_linearity_threshold" default="0.1"/>
  <arg name="rosbag_start" default="0"/>
  <arg name="rosbag_end" default="200"/>

  
  <node name="afl_lidarOdometry" pkg="afli_calib" type="afl_lidarOdometry" output="screen">
    <param name="rosbag_path" value="$(arg rosbag_path)"/>
    <param name="lidar_type" value="$(arg lidar_type)"/>
    <param name="lidar_topic" value="$(arg lidar_topic)"/>
    <param name="match_stability_threshold" value="$(arg match_stability_threshold)"/>
    <param name="motion_linearity_threshold" value="$(arg motion_linearity_threshold)"/>
    <param name="rosbag_start" value="$(arg rosbag_start)"/>
    <param name="rosbag_end" value="$(arg rosbag_end)"/>
  </node>
</launch>

**Comment by wuming122333** [comment]
rosrun 启动提示问题如下：
wolfy@wolfy-DELL:~/calib/AFLI_Calib$ rosrun afli_calib afl_lidarOdometry /media/wolfy/DATA/test_RS2VLP.bag 2 /velodyne_points 0.5 0.1 0 60
Multi thread started 
Let's start!
the bag processed is: test_RS2VLP.bag
the lidar type is: vlp-16!
the lidar topic is: /velodyne_points
match_stability_threshold: 0.5
motion_linearity_threshold: 0.1
bag start: 0
bag_dur: 60
we start load data!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
vlp-16!
lidar data size:0
imu data size:27589
imu dt: 0.00999982s
Load Data time consume: 19.1033 s
all lidar point size:0
we start adaptive frame length LiDAR odometry!
段错误 (核心已转储)
wolfy@wolfy-DELL:~/calib/AFLI_Calib$

**Comment by wuming122333** [comment]
bag包具体参数：
32线雷达
wolfy@wolfy-DELL:/media/wolfy/DATA$ rosbag info test_RS2VLP.bag 
path:        test_RS2VLP.bag
version:     2.0
duration:    4:35s (275s)
start:       Jan 19 2024 01:00:51.68 (1705597251.68)
end:         Jan 19 2024 01:05:27.55 (1705597527.55)
size:        8.5 GB
messages:    33092
compression: none [5504/5504 chunks]
types:       sensor_msgs/Imu         [6a62c6daae103f4ff57a132d6f95cec2]
             sensor_msgs/PointCloud2 [1158d486dd51d683ce2f1be655c3c181]
topics:      /imu/data          27589 msgs    : sensor_msgs/Imu        
             /rslidar_points     2759 msgs    : sensor_msgs/PointCloud2
             /velodyne_points    2744 msgs    : sensor_msgs/PointCloud2

**Comment by wwtinwhu** [comment]
Thanks for your test! The current version does not support Velodyne LiDAR, only the API interface is left: https://github.com/DCSI2022/AFLI_Calib/blob/f9f04e0da90b9c57ef03a58c15daad8d6dbfac49/include/io.cpp#L91-L120

**Comment by wuming122333** [comment]
请问如果我想适配velodyne或者其他类型的雷达，是否只需要在点云预处理部分增加相应雷达结构就可以

**Comment by wwtinwhu** [comment]
> Quote reply

是的，欢迎提交pull request！

**Comment by wuming122333** [comment]
仍然提示错误：
wolfy@wolfy-DELL:~/calib/AFLI_Calib$ rosrun afli_calib afl_lidarOdometry /media/wolfy/DATA/test_RS2VLP.bag 2 /velodyne_points 0.5 0.1 0 60
Multi thread started 
Let's start!
the bag processed is: test_RS2VLP.bag
the lidar type is: vlp-16!
the lidar topic is: /velodyne_points
match_stability_threshold: 0.5
motion_linearity_threshold: 0.1
bag start: 0
bag_dur: 60
we start load data!
lidar data size:600
imu data size:27589
imu dt: 0.00999982s
Load Data time consume: 22.3284 s
all lidar point size:11169872
we start adaptive frame length LiDAR odometry!
start build kdtree
kdtree build success
adaptive frame point size: 11169872
after downsample size: 232328
free(): double free detected in tcache 2
已放弃 (核心已转储)

**Comment by wwtinwhu** [comment]
Adaptive frame point size is consistent with all lidar point size, which indicates that there is a problem with the timestamp of the laser points.

**Comment by wwtinwhu** [comment]
Any update? @wuming122333
