### ISSUE TITLE
标定

### ISSUE THREAD

**Issue by pedestrain123** [DCSI2022/AFLI_Calib#3]
您好请问，这个代码可以用来标定lidar和gnss(rtk)的外参吗？并且采集数据由于车辆比较大只能做平面运动，可以绕8字采集数据，期待您的回复

**Comment by wwtinwhu** [comment]
@pedestrain123 您好，这个项目的输入是LiDAR帧和IMU测量数据，需要充分的6自由度运动激励。我之前标定过车载LiDAR和GNSS/INS的外参，可以[邮件](https://github.com/wwtinwhu)进一步交流 :)

**Comment by pedestrain123** [comment]
> @pedestrain123 您好，这个项目的输入是LiDAR帧和IMU测量数据，需要充分的6自由度运动激励。我之前标定过车载LiDAR和GNSS/INS的外参，可以[邮件](https://github.com/wwtinwhu)进一步交流 :)
好的感谢您的回复，方便的话可以加一下您的qq吗？或者其他联系方式，我的QQ是2985782675。最近在搞lidar gnss标定，希望能和您交流一下

**Comment by pedestrain123** [comment]
@wwtinwhu

**Comment by pedestrain123** [comment]
好的感谢您的回复，方便的话可以加一下您的qq吗？或者其他联系方式，我的QQ是2985782675。最近在搞lidar gnss标定，希望能和您交流一下@wwtinwhu
